// This is generated by the overlay tool - DO NOT EDIT.

#ifndef TRAMPOLINE_H
#define TRAMPOLINE_H

void FAR8_firstSegment(int arg1, int arg2);
void FAR9_secondSegment(int arg1, int arg2);
void FAR8_moreFirstSegment(int arg1, int arg2);

#endif // TRAMPOLINE_H
